name: workflow-fork.yml
on: fork

jobs:
  fork-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        env:
          FORKER: ${{ github.actor }}
        run: echo "$FORKER has forked the project"
