name: workflow-issue.yml
on:
  issues:
    types:
      - opened
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: issue auto-response
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          AUTHOR_NAME: ${{ github.event.issue.user.login }}
          ISSUE_NAME: ${{ github.event.issue.title }}
        run: gh issue comment $ISSUE_URL --body "Hi $AUTHOR_NAME! Thanks for opening '$ISSUE_NAME' our team will respond to you soon."
